name: CI tests
on:
  push:
    branches:
      - 'main'

env:
  MODEL_BUCKET: 'taxi-streaming-model'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v0.7.3
      #   with:
      #     token_format: 'access_token' # <--
      #     workload_identity_provider: 'projects/277007001518/locations/global/workloadIdentityPools/ga-pool/providers/my-provider'
      #     service_account: 'terraform@mlops-zoomcamp-352510.iam.serviceaccounts.com'

      - name: Setup service credentials
        run: echo -e '${{ secrets.GCP_SERVICE_CREDENTIALS }}' > function/service-account.json
      - name: Install Dependencies
        working-directory: "function"
        run: pip install pipenv && pipenv install --dev --python 3.9.13

      - name: lint
        working-directory: "function"
        run: pipenv run pylint --recursive=y .

      - name: Run tests
        working-directory: "function"
        run: |
          echo $(cat service-account.json)
          pipenv run pytest
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2

      - name: Setup credentials
        run: |
          echo -e '${{ secrets.GCP_SERVICE_CREDENTIALS }}' > function/service-account.json
          echo -e '${{ secrets.GCP_TERRAFORM_CREDENTIALS }}' > function/infrastructure/terraform-account.json
      - name: Test credentials
        working-directory: "function/infrastructure"
        run : |
          echo $(cat ./terraform-account.json)
      - name: TF plan
        id: plan
        working-directory: "function/infrastructure"
        run: |
          echo $(ls)
          terraform init -backend-config="prefix="tfstate-prod""
          terraform plan --var-file vars/prod.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_TERRAFORM_CREDENTIALS}}
