name: CI tests
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'function/**'

env:
  MODEL_BUCKET: 'taxi-streaming-model'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v0.7.3
      #   with:
      #     token_format: 'access_token' # <--
      #     workload_identity_provider: 'projects/277007001518/locations/global/workloadIdentityPools/ga-pool/providers/my-provider'
      #     service_account: 'terraform@mlops-zoomcamp-352510.iam.serviceaccounts.com'

      - name: Setup service credentials
        run: echo -e '${{ secrets.GCP_SERVICE_CREDENTIALS }}' >> function/service-account.json
      - name: Install Dependencies
        working-directory: "function"
        run: pip install pipenv && pipenv install --dev

      - name: lint
        working-directory: "function"
        run: pipenv run pylint --recursive=y

      - name: Run tests
        working-directory: "function"
        run: pipenv run pytest

  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2

      - name: Setup credentials
        run: |
          echo -e '${{ secrets.GCP_SERVICE_CREDENTIALS }}' >> function/service-account.json
          echo -e '${{ secrets.GCP_TERRAFORM_CREDENTIALS }}' >> function/infrastructure/terraform-account.json
      - name: TF plan
        id: plan
        working-directory: "function/infrastructure"
        run:
          terraform init -backend-config="key=mlops-zoomcamp-prod.tfstate" && terraform plan --var-file vars/prod.tfvars
